project:
  type: book
  output-dir: docs

book:
  title: "Powering Institutional Research with R"
  author: 
    - name: Thomas Jay Benjamin
      affiliation: 
        - name: Lorain County Community College
          department: Institutional Research
          city: Elyria
          state: OH
          country: US
          url: https://www.lorainccc.edu
    - name: Lynzee Murray
      affiliation: Columbus State Community College
      affiliation-url: https://www.cscc.edu
  date: "10/19/2023"
  cover-image: cover.png
  favicon: favicon.ico
  chapters:
    - index.qmd
    - intro.qmd
    - workingwithdata.qmd
    - analysis.qmd
    - reports.qmd
    - collaboration.qmd
    - references.qmd
  appendices:
    - examplebasicquarto.qmd
    - examplefullquartoreport.qmd
    - exampleparameterizedreport.qmd
  page-navigation: true
  reader-mode: true
  page-footer:
    background: light
    left: Proudly supported by [![](https://oairp.org/resources/Pictures/oairp-lite.png){height=20px}](https://www.oairp.org/)
    center:
      - text: "About the authors"
        href: about.qmd
      - text: "Acknowledgements"
        href: acknowledgements.qmd
    right: This guide was built with [Quarto](https://quarto.org)
  repo-url: https://github.com/oairp/PoweringIRwithR
  site-url: https://oairp.github.io/PoweringIRwithR/
  repo-actions: [issue]
  downloads: [epub]
  sharing: [twitter, facebook, linkedin]
  open-graph:
    image: cover.png


citation:
  type: book
google-scholar: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 2
  epub:
    cover-image: cover.png



